apiVersion: v1
kind: Namespace
metadata:
  annotations:
    oneagent.dynatrace.com/technologies: "java"
    oneagent.dynatrace.com/inject: "false"
  labels:
    oneagent.dynatrace.com/instance: oneagentapm
  name: easytravel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-backend
  name: easytravel-backend
  namespace: easytravel
spec:
  replicas: 2
  selector:
    matchLabels:
      easytravel-tier: easytravel-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "true"
      labels:
        easytravel-tier: easytravel-backend
        tier: backend
      name: easytravel-backend
    spec:
      containers:
        - env:
            - name: ET_DATABASE_LOCATION
              value: easytravel-mongodb-service:27017
            - name: ET_MONGO_AUTH_DB
              value: admin
            - name: ET_DATABASE_USER
              value: etAdmin
            - name: ET_DATABASE_PASSWORD
              value: adminadmin
            - name: DT_CLUSTER_ID
              value: easytravel-backend
          image: ccr.ccs.tencentyun.com/dynatrace/easytravel-backend
          resources:
            limits:
              cpu: "1"
              memory: "2048Mi"
            requests:
              cpu: "0.5"
              memory: "1024Mi"
          imagePullPolicy: Always
          name: easytravel-backend
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-frontend
  name: easytravel-frontend
  namespace: easytravel
spec:
  replicas: 3
  selector:
    matchLabels:
      easytravel-tier: easytravel-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "false"
      labels:
        easytravel-tier: easytravel-frontend
        tier: frontend
    spec:
      containers:
        - env:
            - name: ET_BACKEND_URL
              value: http://easytravel-backend-service:8080
            - name: DT_CLUSTER_ID
              value: easytravel-frontend
          image: ccr.ccs.tencentyun.com/dynatrace/easytravel-frontend
          resources:
            limits:
              cpu: "1"
              memory: "4096Mi"
            requests:
              cpu: "0.5"
              memory: "1024Mi"
          imagePullPolicy: Always
          name: easytravel-frontend
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-nginx
  name: easytravel-nginx
  namespace: easytravel
spec:
  replicas: 2
  selector:
    matchLabels:
      easytravel-tier: easytravel-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/technologies: "nginx"
        oneagent.dynatrace.com/inject: "true"
      labels:
        easytravel-tier: easytravel-nginx
        tier: nginx
    spec:
      containers:
        - env:
            - name: ET_FRONTEND_LOCATION
              value: easytravel-frontend-service:8080
            - name: ET_BACKEND_LOCATION
              value: easytravel-backend-service:8080
            - name: DT_CLUSTER_ID
              value: easytravel-nginx
          image: ccr.ccs.tencentyun.com/dynatrace/easytravel-nginx
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          imagePullPolicy: Always
          name: easytravel-nginx
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-mongodb
  name: easytravel-mongodb
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      easytravel-tier: easytravel-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        easytravel-tier: easytravel-mongodb
      labels:
        easytravel-tier: easytravel-mongodb
        tier: database
    spec:
      containers:
        - env:
            - name: DT_CLUSTER_ID
              value: easytravel-mongodb
          image: ccr.ccs.tencentyun.com/dynatrace/easytravel-mongodb
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          name: easytravel-mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
            - containerPort: 28017
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgenerator
  name: loadgenerator
  namespace: easytravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "true"
      labels:
        app: loadgenerator
    spec:
      containers:
        - env:
            - name: ET_WWW_URL
              value: http://easytravel-nginx-service:80
            - name: ET_FRONTEND_URL
              value: http://easytravel-frontend-service:8080
            - name: ET_BACKEND_URL
              value: http://easytravel-backend-service:8080
            - name: ET_PROBLEMS_DELAY
              value: "7500"
            - name: ET_VISIT_NUMBER
              value: "5"
            - name: DT_CLUSTER_ID
              value: easytravel-loadgen
            - name: ET_PROBLEMS
              value: BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox
          image: ccr.ccs.tencentyun.com/dynatrace/easytravel-loadgen
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          name: easytravel-loadgen
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-backend-service
  name: easytravel-backend-service
  namespace: easytravel
spec:
  ports:
    - name: port5
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    easytravel-tier: easytravel-backend
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-frontend
  name: easytravel-frontend-service
  namespace: easytravel
spec:
  ports:
    - name: port1
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    easytravel-tier: easytravel-frontend
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-nginx
  name: easytravel-nginx-service
  namespace: easytravel
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: port1
      port: 80
      protocol: TCP
      targetPort: 80
    - name: port2
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    easytravel-tier: easytravel-nginx
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-mongodb
  name: easytravel-mongodb-service
  namespace: easytravel
spec:
  ports:
    - name: "27017"
      port: 27017
      protocol: TCP
      targetPort: 27017
    - name: "28017"
      port: 28017
      protocol: TCP
      targetPort: 28017
  selector:
    easytravel-tier: easytravel-mongodb
  sessionAffinity: None
  type: ClusterIP
